FROM debian:trixie-slim

# renovate: suite=trixie depName=borgbackup
ENV BORGBACKUP_VERSION="1.4.0-5"

ENV BORG_BASE_DIR=/borg

RUN apt-get update && \
    apt-get install -y \
    borgbackup="${BORGBACKUP_VERSION}" && \
    apt-get clean