apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-backup.fullname" . }}-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-newfs