apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-backup.fullname" . }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "k8s-backup.fullname" . }}
      containers:
      - name: backup
        image: ghcr.io/flx5/k8s-borg/backup:main@sha256:7b4388102ba876efeaefa8b1591721166ba6ecc3b1a662782081e94adb45878e
        command:
        - "python3"
        - -c
        - |
          from backup import BackupContext, SnapshotInfo
          from main import BackupDefinition, create_backup


          class MyBackup(BackupDefinition):
            def prepare_snapshots(self, ctx: BackupContext) -> dict[str, SnapshotInfo]:
              {{- .Values.prepareBackupScript | nindent 14 }}

            def scratch_volume(self) -> str | None:
                return {{ if .Values.scratch.enabled }} {{ include "k8s-backup.scratchName" . | quote }} {{ else }} None {{ end }}
        
            def application(self) -> str | None:
                return {{ .Release.Name | quote }}

          create_backup(MyBackup())
      restartPolicy: Never
  backoffLimit: 0