{{ if .Values.scratch.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-backup.scratchName" . }}
  finalizers: []
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-newfs
{{ end }}